user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name _DOMAIN_NAME_;

        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;


         root /var/www/html;
         index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # ACTUALLY SETUP ONCE YOU DO WORDPRESS
#        location ~ \.php$ {
#            # Check if the php file actually exists before passing it
#            try_files $uri =404;
#
#            # Forward the request to the 'wordpress' service on port 9000
#            fastcgi_pass wordpress:9000;
#
#            # Standard FastCGI setup
#            include fastcgi_params;
#            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#        }
    }
}