version: '3.8'

services:
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION:-3.23}
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
# TODO: mariadb & nginx

networks:
  inception_net:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dotacow/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dotacow/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt