services:
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        - ALPINE_VERSION=${ALPINE_VERSION:-3.23}
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_net
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root", "--path=/var/www/html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - ALPINE_VERSION=${ALPINE_VERSION:-3.23}
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "root", "-p$$(cat /run/secrets/db_root_password)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


# TODO:  nginx

networks:
  inception_net:
    name: inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt